<!DOCTYPE html>
<html>
<head>
    <title>Houses</title>
    <link rel="stylesheet" href="styles.css">
    <style>
        body {
    background-color: #111;
    color: #fff;
}

.house-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}

.house-box {
    width: 30%;
    background-color: #222;
    border-radius: 5px;
    margin-bottom: 20px;
    padding: 20px;
}

.house-box img {
    width: 100%;
    border-radius: 5px;
    margin-bottom: 10px;
}

.house-box h3 {
    font-size: 20px;
    margin-bottom: 10px;
}

.house-box p.description {
    margin-bottom: 10px;
}

.btn-show-description {
    background-color: #333;
    color: #fff;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
}

.description-box {
    display: none;
    background-color: #444;
    padding: 10px;
    margin-top: 10px;
    border-radius: 5px;
    color: #fff;
}

/* Additional styling for dark mode */
a {
    color: #fff;
}

a:hover {
    color: #aaa;
}

button {
    background-color: #333;
    color: #fff;
}

button:hover {
    background-color: #555;
}

input[type="text"],
textarea {
    background-color: #222;
    color: #fff;
    border: 1px solid #555;
}

input[type="text"]:focus,
textarea:focus {
    border-color: #aaa;
}

input[type="submit"] {
    background-color: #333;
    color: #fff;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
}

input[type="submit"]:hover {
    background-color: #555;
}

    </style>
</head>
<body>
    <div class="house-container">
        <!-- House cards will be dynamically generated by the PHP code -->
        <?php include 'display_houses.php'; ?>
        <div id="calendar"></div>
    </div>

    <script>
        // JavaScript code to handle the button click event
        document.addEventListener('DOMContentLoaded', function() {
            var showDescriptionButtons = document.getElementsByClassName('btn-show-description');
            for (var i = 0; i < showDescriptionButtons.length; i++) {
                showDescriptionButtons[i].addEventListener('click', function() {
                    var container = this.parentNode;
                    var descriptionBox = container.getElementsByClassName('description-box')[0];

                    // Toggle visibility of the description box
                    if (descriptionBox.style.display === 'none') {
                        descriptionBox.style.display = 'block';
                    } else {
                        descriptionBox.style.display = 'none';
                    }
                });
            }
        });
    </script>
    <script src="script.js"></script>
</body>
</html>
